services:
  #Backend - FastAPI application
  backend:
    build:
      context: .
      dockerfile: Dockerfile.bot

    ports:
      - "8060:80"

    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}

    expose:
      - "80"

  #Frontend - Streamlit application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"

    environment:
      - BACKEND_URL=http://backend:80

    depends_on:
      - backend

networks:
  default:
    driver: bridge